####### NGX - XTicket Config #########
---
server:
    error:
        include-message: never
        include-binding-errors: always
        include-exception: false
        include-stacktrace: never
    tomcat:
        basedir: C:/XTicket/Log
        accesslog:
            enabled: true
    temp:
        dir: C:/XTicket/temp
    connection-timeout: 120000

logging:
    file:
        name: C:/Xticket/logs/xticket.log
    level:
        root: INFO
upload:
    base:
        dir: C:/Xticket/bulk/upload
    max:
        record: 100
jwt:
    security:
        key: j3H5Ld5nYmGWyULy6xwpOgfSH++NgKXnJMq20vpfd+8=t
    access:
        validity: 60000
             
spring:
    cloud:
        loadbalancer:
            ribbon:
                enabled: false
    config:
        activate:
            profile: dev
    datasource:
        initialization-mode: ALWAYS
        password: Anaconda1521@ 
        username: entityscdbuser
        driverClassName: com.microsoft.sqlserver.jdbc.SQLServerDriver
        url: jdbc:sqlserver://localhost;databaseName=XTicket;encrypt=true;trustServerCertificate=true
    jpa:
        hibernate:
            ddl-auto: update
            dialect: org.hibernate.dialect.SQLServerDialect
        show-sql: false

email:
    host: 10.172.16.170
    port: 25
    protocol: smtp
    trust: 10.172.16.170
    login: postmaster@ngxgroup.com
    from: X-Ticket
    password: Password10$
    
xticket:
  holiday: 2024-01-01,2024-03-29,2024-04-01,2024-04-10,2024-04-11,2024-05-01,2024-06-12,2024-06-16,2024-09-16,2024-10-10,2024-12-25,2024-12-26
  escalation:
    wait:
      time: 2
      unit: minutes #This should be either hours or minutes
  slaexpiry:
    notification: 5 #Notification sent 5 mins or less to SLA expiry
    timeleft: 5 #Time left before ticket SLA is violated
    exceeded: 60  #Tickets closed in <= 60% of the alloted time
  office:
    open: 8
    close: 17
  adauth:
    domains: ngxgroup.com, brokers.ngxgroup.com  
  host: 'https://testapp.ngxgroup.com:8443'
  company:
    name: Nigerian Exchange Group
    address: 2 Custom Street, Marina, Lagos
    email: info@ngxgroup.com
    phone: 01-270388738
    rc: 123454
    logo: kalis
  cron:
    job: 
      ticketrun: '*/2 * * * * ?' #This cron job runs every 2 minutes
      automatedticket: '0 17 * * * ?' #This cron job runs every 9am
  email:
    contactus: coordination@ngxgroup.com
    escalation:
      interval: 5 #This is 5 minutes between escalation
    notification: bokon@ngxgroup.com
  expiry:
    days: 3
  download:
    policy:
      base:
        dir: C:/NGX/XTicket
  default:
    entitycode: NGX
    entityname: Nigerian Exchange Group
    departmentcode: DEF
    departmentname: Default Department
    password: Password!23#
    email:
      domain: ngxgroup.com
    dc:
      group: ngxgroup.com
      regulation: regulation.ngxgroup.com
      realestate: exchange.ngxgroup.com
      limited: exchange.ngxgroup.com
  qrcode:
    height: 115
    width: 115
    image:
      url: C:/Apps/Java/XTicket/target/xticket-1.0/WEB-INF/classes/images/qrcode
  password:
    pattern: ^(?=.*\d)(?=.*[a-zA-Z])(?=.*[A-Z])(?=.*[-\#\$\.\%\&\*\@])(?=.*[a-zA-Z]).{8,16}$
    default: Password23#
    reset:
      time: 1
    retry:
      count: 3
    change:
      days: 30
  encryption:
    key:
      mian: FLWSECK-f6be2996841f1da0dfb7e27b9a3bd5bf-X
      web: yG4b7jm8NHkv8s0vfwaS