####### NGX - XTicket Config #########
---
server:
    servlet:
        session:
            timeout: 300  #This is 300 seconds (5 minutes)
    error:
        include-message: never
        include-binding-errors: always
        include-exception: false
        include-stacktrace: never
    tomcat:
        basedir: C:/XTicket/Log
        accesslog:
            enabled: true
    temp:
        dir: C:/XTicket/temp
    connection-timeout: 120000
    
management:
    info:
        os:
            enabled: true
        java:
            enabled: true
        env:
            enabled: true
    endpoints:
        sessions:
            enabled: true
        web:
            exposure:
                include: '*'

logging:
    file:
        name: C:/Xticket/logs/xticket.log
    level:
        root: INFO
upload:
    base:
        dir: C:/Xticket/bulk/upload
    max:
        record: 100
jwt:
    security:
        key: j3H5Ld5nYmGWyULy6xwpOgfSH++NgKXnJMq20vpfd+8=t
    access:
        validity: 60000
             
spring:
    session:
        store-type: jdbc
        jdbc:
            initialize-schema: always
            schema: classpath:org/springframework/session/jdbc/schema-@@platform@@.sql
    cloud:
        loadbalancer:
            ribbon:
                enabled: false
    config:
        activate:
            profile: dev
    datasource:
        initialization-mode: ALWAYS
        password: qwerty@1 
        username: xcdev
        driverClassName: com.microsoft.sqlserver.jdbc.SQLServerDriver
        url: jdbc:sqlserver://10.172.16.145\XBRDB;databaseName=XTicket;encrypt=true;trustServerCertificate=true;
        #password: F3bru@ry02mth
        #username: admin
        #driverClassName: com.mysql.jdbc.Driver
        #url: jdbc:mysql://10.172.16.221:3306/xticket?allowPublicKeyRetrieval=true&useSSL=false
    jpa:
        hibernate:
            ddl-auto: update
            dialect: org.hibernate.dialect.SQLServerDialect
            #dialect: org.hibernate.dialect.MySQL8Dialect
        show-sql: false

email:
    host: 10.172.16.170
    port: 25
    protocol: smtp
    trust: 10.172.16.170
    login: postmaster@ngxgroup.com
    from: X-Ticket
    password: Password10$
    
xticket:
  escalation:
    wait:
      time: 2
      unit: minutes #This should be either hours or minutes
  slaexpiry:
    notification: 5 #Notification sent 5 mins or less to SLA expiry
    timeleft: 5 #Time left to SLA Violation. Use to determine criticality
    exceeded: 60  #Tickets closed in <= 60% of the alloted time
  office:
    open: 8
    close: 17
  adauth:
    domains: ngxgroup.com, brokers.ngxgroup.com  
  host: 'http://localhost:8082'
  company:
    name: Nigerian Exchange Group
    address: 2 Custom Street, Marina, Lagos
    email: info@ngxgroup.com
    phone: 01-270388738
    rc: 123454
    logo: kalis
  cron:
    job: 
      ticketrun: '*/2 * * * * ?' #This cron job runs every 2 minutes
      automatedticket: '0 9 * * * ?' #This cron job runs every 9am
  email:
    contactus: coordination@ngxgroup.com
    escalation:
      interval: 5 #This is 5 minutes between escalation
    notification: bokon@ngxgroup.com
  expiry:
    days: 3
  download:
    policy:
      base:
        dir: C:/NGX/XTicket
  default:
    notification:
      push: A new push notification received
      ticket: You have a new ticket request
    entitycode: NGX
    entityname: Nigerian Exchange Group
    departmentcode: DEF
    departmentname: Default Department
    password: Password!23#
    email:
      domain: ngxgroup.com
    dc:
      group: ngxgroup.com
      regulation: regulation.ngxgroup.com
      realestate: exchange.ngxgroup.com
      limited: exchange.ngxgroup.com
  qrcode:
    height: 115
    width: 115
    image:
      url: C:/Apps/Java/XTicket/target/xticket-1.0/WEB-INF/classes/images/qrcode
  password:
    pattern: ^(?=.*\d)(?=.*[a-zA-Z])(?=.*[A-Z])(?=.*[-\#\$\.\%\&\*\@])(?=.*[a-zA-Z]).{8,16}$
    default: Password23#
    reset:
      time: 1
    retry:
      count: 3
    change:
      days: 30
  encryption:
    key:
      mian: FLWSECK-f6be2996841f1da0dfb7e27b9a3bd5bf-X
      web: yG4b7jm8NHkv8s0vfwaS
